Config
Volkalex28/InternProject pull request #3
Opened 2021-01-12 17:22 UTC by Volkalex28

First pull request. Added initialisation rcc, gpio and UART. Added Reseive and Transmit

2021-01-12 17:54 UTC, d-serj requested changes
Please, fix all the remarks that are not marked as `Minor`

2021-01-12 17:54 UTC, d-serj commented on Core/Src/main.c
>  int main() {
Place brackets `{` on the new line

2021-01-12 17:54 UTC, d-serj commented on Core/Src/main.c
> +    UART1_Transmit(buf, strlen((char*)buf), 1000);// == 0 ? GPIO_SetPin(LED_GREEN_Port, LED_GREEN_Pin) : GPIO_ResetPin(LED_GREEN_Port, LED_GREEN_Pin);
Remove the comments or add a comment with a description of why you left them

2021-01-12 17:54 UTC, d-serj commented on Drivers/CMSIS/Device/ST/STM32F0xx/Include/stm32f0xx.h
> +  * - Product miscellaneous configuration: assert macros�
Please, revert changes of these lines with an unknown symbol

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_rcc.c
> + * @retval None
Minor: you can omit `@retval` or `@return` comments if the function returns nothing

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_rcc.c
> +  while(ticks < (tickStart + timeout));
Minor: Most likely that the function with the loop inside won't be inlined. You can check it with compilation flag `-Winline`

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +} uart1;
Please, declare structures at the beginning of the source or header file

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +      uint16_t  data = READ_REG(USART1->RDR);
Add `const` qualifier since `data` is read-only variable

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +  //uint32_t cr3its     = READ_REG(USART1->CR3);
Remove the comment or add a description of why you commented out this line

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +  if(READ_BIT(isrflags, USART_ISR_PE | USART_ISR_FE | USART_ISR_ORE | USART_ISR_NE | USART_ISR_RTOF) == 0)
You can decrease the level of nesting
```
if (READ_BIT(isrflags, USART_ISR_PE | USART_ISR_FE
    | USART_ISR_ORE | USART_ISR_NE | USART_ISR_RTOF) != 0)
{
  return;
}
```

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +    if(READ_BIT(isrflags, USART_ISR_RXNE) != 0 && READ_BIT(cr1its, USART_CR1_RXNEIE) != 0)
Despite you know the operator's priority I would recommend covering all conditions with extra brackets.
`if ((READ_BIT(isrflags, USART_ISR_RXNE) != 0) && (READ_BIT(cr1its, USART_CR1_RXNEIE) != 0)) `

2021-01-12 17:54 UTC, d-serj commented on Drivers/STM32F051_Driver/Src/stm32f051_uart.c
> +  if((READ_BIT(USART1->CR1, USART_CR1_RE) ? SET : RESET) != RESET)
Here you check the result to be `SET` or `RESET`, but in other places you compare it to just `0`
Please, make all the checks by `READ_BIT` in one style.

2021-01-12 17:54 UTC, d-serj commented on Core/Inc/main.h
> +#define LED_BLUE_Pin    GPIO_PIN_8
Create separated file named `pins.h` and move all pins definitions to that file

2021-01-12 17:54 UTC, d-serj commented on Core/Inc/main.h
> +#include "stm32f051_uart.h"
All includes, if we do not need them to be included in the header file, must be moved to related source files

2021-01-13 12:13 UTC, Volkalex28 commented
Errors corrected

2021-01-13 12:16 UTC, d-serj approved these changes
Please, merge the pull request

2021-01-13 12:17 UTC, merged